# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
royhat = [1, 2, 3, 4, 5]
massiv = np.array(royhat)
massiv

array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [ ]:
# 9 o'lchovli nol massiv yaratish
array = np.zeros((1, 1, 1, 1, 1, 1, 1, 1, 1))

print(array)
print("Massiv o'lchami:", array.shape)

[[[[[[[[[0.]]]]]]]]]
Massiv o'lchami: (1, 1, 1, 1, 1, 1, 1, 1, 1)


`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
# 9 o'lchovli massiv (tasodifiy sonlar bilan)
array = np.random.rand(2, 2, 2, 2, 2, 2, 2, 2, 2)

# Massivning umumiy elementlar soni
total_elements = array.size

# Bitta element egallagan xotira hajmi (baytlarda)
element_size = array.itemsize

# Umumiy xotira hajmi (baytlarda)
memory_size = total_elements * element_size

print("Elementlar soni:", total_elements)
print("Bitta element hajmi:", element_size, "bayt")
print("Umumiy xotira hajmi:", memory_size, "bayt")

Elementlar soni: 512
Bitta element hajmi: 8 bayt
Umumiy xotira hajmi: 4096 bayt


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
# 12 o'lchovli vektor yaratish (barcha qiymatlar 0 bo'lsin)
array = np.zeros(12)

# Vektorning oltinchi qiymatini 1 ga tenglashtirish
array[5] = 1  # Indeks 5, chunki Python 0-dan boshlanadi

print(array)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr = np.arange(20, 60)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
# Vektor yaratish
array = np.arange(1, 11)

# Vektorning teskari ko'rinishi
reversed_array = array[::-1]

print("Asl vektor:", array)
print("Teskari vektor:", reversed_array)

Asl vektor: [ 1  2  3  4  5  6  7  8  9 10]
Teskari vektor: [10  9  8  7  6  5  4  3  2  1]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
# 12 dan 20 gacha bo'lgan qiymatlarni yaratish
array = np.arange(12, 21)

# 3x3 matritsaga o'zgartirish
matrix = array.reshape(3, 3)

print(matrix)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
# Berilgan matritsa (vektor)
array = np.array([3, 7, 0, 0, 9, 0])

# Nolga teng bo'lmagan elementlarning indekslarini topish
indices = np.nonzero(array)

print("Nolga teng bo'lmagan elementlarning indekslari:", indices[0])

Nolga teng bo'lmagan elementlarning indekslari: [0 1 4]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
# 2x2x2 o'lchovli tasodifiy massiv yaratish
array = np.random.random((2, 2, 2))

print(array)

[[[0.16316351 0.78296057]
  [0.81669609 0.95299975]]

 [[0.40966566 0.51552682]
  [0.38456517 0.94658784]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:


# 9x9 o'lchamdagi tasodifiy massiv yaratish
array = np.random.random((9, 9))  # 0 va 1 oralig‘ida tasodifiy sonlar

# Eng katta va eng kichik qiymatlarni topish
max_value = array.max()  # Eng katta qiymat
min_value = array.min()  # Eng kichik qiymat

# Natijani chiqarish
print("Massiv:\n", array)
print("\nEng katta qiymat:", max_value)
print("Eng kichik qiymat:", min_value)


Massiv:
 [[0.28884351 0.07563025 0.49110115 0.87437085 0.67892797 0.75310759
  0.84259641 0.66917143 0.24984985]
 [0.60184992 0.67792047 0.56104506 0.82685909 0.81676304 0.91424123
  0.38200115 0.41869061 0.52838983]
 [0.60117062 0.7817888  0.27978799 0.34989957 0.24995166 0.67616359
  0.38687365 0.52447171 0.12015175]
 [0.49805462 0.91823951 0.14059273 0.61070094 0.90364054 0.72380367
  0.46145151 0.35804876 0.04843835]
 [0.49534441 0.74442998 0.52541011 0.36634694 0.65801752 0.88355125
  0.69372955 0.76491498 0.41350559]
 [0.26226826 0.6181191  0.06699606 0.02070702 0.56243715 0.28686855
  0.46764562 0.57675104 0.32477463]
 [0.85644526 0.27640941 0.01262999 0.76704311 0.11761214 0.98323981
  0.23974722 0.23180685 0.43024886]
 [0.54186616 0.87372263 0.95283292 0.75738748 0.03261366 0.01261061
  0.38013609 0.50164149 0.28652689]
 [0.37206914 0.84133979 0.59049426 0.31076458 0.5440785  0.77156703
  0.46712026 0.85866796 0.33701216]]

Eng katta qiymat: 0.9832398091153708
Eng kichik qiyma

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.7 == 7 * 0.1 # False


False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
import numpy as np

# 6x3 o'lchamdagi matritsa
A = np.ones((6, 3))  # Barcha elementlari 1 bo'lgan matritsa

# 3x4 o'lchamdagi matritsa
B = np.ones((3, 4))  # Barcha elementlari 1 bo'lgan matritsa

# Matritsalar ko'paytmasi
C = np.dot(A, B)

print("6x3 matritsa:\n", A)
print("\n3x4 matritsa:\n", B)
print("\nKo'paytma (6x4 matritsa):\n", C)


6x3 matritsa:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3x4 matritsa:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Ko'paytma (6x4 matritsa):
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:


# Massivlarni yaratamiz
a = np.array([1, 2])
b = np.array([4, 5])

# Taqqoslash amallari
print("a > b  :", a > b)   # [False False]
print("a >= b :", a >= b)  # [False False]
print("a < b  :", a < b)   # [ True  True]
print("a <= b :", a <= b)  # [ True  True]


a > b  : [False False]
a >= b : [False False]
a < b  : [ True  True]
a <= b : [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:



# 1. np.array(0) / np.array(0)
try:
    result_1 = np.array(0) / np.array(0)
    print("Natija 1:", result_1)
except Exception as e:
    print("Natija 1 (xato):", e)

# 2. np.array(0) // np.array(0)
try:
    result_2 = np.array(0) // np.array(0)
    print("Natija 2:", result_2)
except Exception as e:
    print("Natija 2 (xato):", e)

# 3. np.array([np.nan]).astype(int).astype(float)
try:
    result_3 = np.array([np.nan]).astype(int).astype(float)
    print("Natija 3:", result_3)
except Exception as e:
    print("Natija 3 (xato):", e)



Natija 1: nan
Natija 2: 0
Natija 3: [-9.22337204e+18]


<ipython-input-28-a2748003a49a>:3: RuntimeWarning: invalid value encountered in divide
  result_1 = np.array(0) / np.array(0)
<ipython-input-28-a2748003a49a>:10: RuntimeWarning: divide by zero encountered in floor_divide
  result_2 = np.array(0) // np.array(0)
<ipython-input-28-a2748003a49a>:17: RuntimeWarning: invalid value encountered in cast
  result_3 = np.array([np.nan]).astype(int).astype(float)


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
# Ikkita massiv yaratish
massiv_1 = np.array([1, 2, 3, 4, 5])
massiv_2 = np.array([4, 5, 6, 7, 8])

# Umumiy qiymatlarni topish
umumiy_qiymatlar = np.intersect1d(massiv_1, massiv_2)

print("Umumiy qiymatlar:", umumiy_qiymatlar)

Umumiy qiymatlar: [4 5]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:


# Tasodifiy sonlar massivini yaratish
massiv = np.random.uniform(-10, 10, size=10)
print("Tasodifiy massiv:", massiv)

# 1. % operatori bilan butun qismini olish
butun_qism_mod = massiv % 1
print("Mod operatori bilan butun qism:", butun_qism_mod)

# 2. np.floor yordamida butun qismini olish
butun_qism_floor = np.floor(massiv)
print("np.floor yordamida butun qism:", butun_qism_floor)

# 3. astype yordamida butun qismini olish
butun_qism_astype = massiv.astype(int)
print("astype yordamida butun qism:", butun_qism_astype)

# 4. np.trunc yordamida butun qismini olish
butun_qism_trunc = np.trunc(massiv)
print("np.trunc yordamida butun qism:", butun_qism_trunc)


Tasodifiy massiv: [-2.79891294 -9.6182013   0.36392703  0.06269738 -9.90384153 -7.50624809
 -0.88229103 -6.01540038 -1.66173516 -1.1287887 ]
Mod operatori bilan butun qism: [0.20108706 0.3817987  0.36392703 0.06269738 0.09615847 0.49375191
 0.11770897 0.98459962 0.33826484 0.8712113 ]
np.floor yordamida butun qism: [ -3. -10.   0.   0. -10.  -8.  -1.  -7.  -2.  -2.]
astype yordamida butun qism: [-2 -9  0  0 -9 -7  0 -6 -1 -1]
np.trunc yordamida butun qism: [-2. -9.  0.  0. -9. -7. -0. -6. -1. -1.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:


# 0 dan 2 gacha bo'lgan qiymatlar bilan 3x3 matritsa yaratish
matritsa = np.arange(3).reshape(3, 1) + np.arange(3)
print("3x3 matritsa:")
print(matritsa)


3x3 matritsa:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
import numpy as np

# O'lchami 10 bo'lgan tasodifiy vektor yaratish
vektor = np.random.random(10)
print("Tasodifiy vektor:")
print(vektor)

# Vektorni o'sish tartibida saralash
vektor_sorted = np.sort(vektor)
print("\nO'sish tartibida saralangan vektor:")
print(vektor_sorted)


Tasodifiy vektor:
[0.78574388 0.73882416 0.80810772 0.33828656 0.3065806  0.92848253
 0.38892449 0.4914468  0.01336085 0.41700395]

O'sish tartibida saralangan vektor:
[0.01336085 0.3065806  0.33828656 0.38892449 0.41700395 0.4914468
 0.73882416 0.78574388 0.80810772 0.92848253]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
import numpy as np

# Tasodifiy A va B massivlarini yaratish
A = np.random.random(5)
B = np.random.random(5)

print("A massiv:")
print(A)
print("\nB massiv:")
print(B)

# 1. np.allclose yordamida massivlarni tekshirish
if np.allclose(A, B):
    print("\nA va B massivlari teng (np.allclose).")
else:
    print("\nA va B massivlari teng emas (np.allclose).")

# 2. np.array_equal yordamida massivlarni tekshirish
if np.array_equal(A, B):
    print("A va B massivlari teng (np.array_equal).")
else:
    print("A va B massivlari teng emas (np.array_equal).")


A massiv:
[0.17200878 0.57338323 0.09593086 0.10545852 0.14134779]

B massiv:
[0.6787718  0.96831957 0.89016534 0.51417252 0.14189956]

A va B massivlari teng emas (np.allclose).
A va B massivlari teng emas (np.array_equal).


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:


# O'lchamlari 6x3 va 3x4 bo'lgan matritsalarni yaratish
A = np.random.random((6, 3))  # 6x3 matritsa
B = np.random.random((3, 4))  # 3x4 matritsa

print("A matritsa (6x3):")
print(A)
print("\nB matritsa (3x4):")
print(B)

# Matritsalarni o'zaro ko'paytirish
C = np.dot(A, B)
print("\nA va B matritsalari ko'paytmasi (6x4):")
print(C)


A matritsa (6x3):
[[0.56782815 0.61607169 0.73146201]
 [0.95840633 0.35841528 0.85249106]
 [0.14238394 0.25034918 0.34092812]
 [0.93090354 0.58382224 0.45115434]
 [0.34488109 0.46242225 0.13601973]
 [0.98768469 0.49150672 0.29310337]]

B matritsa (3x4):
[[0.40691398 0.15131152 0.59046471 0.43872705]
 [0.96349803 0.76627453 0.32102999 0.67185518]
 [0.02847115 0.14010878 0.07968136 0.4441957 ]]

A va B matritsalari ko'paytmasi (6x4):
[[0.84546664 0.66048323 0.59134386 0.9879448 ]
 [0.75959275 0.5391039  0.74889482 1.0399548 ]
 [0.30885557 0.26114755 0.19160791 0.38210488]
 [0.95415412 0.65143522 0.77303873 1.00105737]
 [0.5897525  0.42558443 0.36292976 0.52240882]
 [0.88381345 0.5671435  0.76433623 0.89374058]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:


# O'lchami 5 ga teng tasodifiy vektor yaratish
vektor = np.random.random(5)
print("Tasodifiy vektor:")
print(vektor)

# Vektorning eng katta qiymatini topish
eng_katta_indeks = np.argmax(vektor)

# Eng katta qiymatini 0 ga o'zgartirish
vektor[eng_katta_indeks] = 0

print("\nEng katta qiymatni 0 ga o'zgartirgandan so'ng vektor:")
print(vektor)


Tasodifiy vektor:
[0.5156952  0.91493498 0.96557161 0.56352381 0.50360444]

Eng katta qiymatni 0 ga o'zgartirgandan so'ng vektor:
[0.5156952  0.91493498 0.         0.56352381 0.50360444]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:


# Bugungi kunni olish
bugun = np.datetime64('today', 'D')
print("Bugun:", bugun)

# Kechani olish (bugundan 1 kun oldin)
kecha = bugun - np.timedelta64(1, 'D')
print("Kecha:", kecha)

# Ertangi kunni olish (bugundan 1 kun keyin)
ertaga = bugun + np.timedelta64(1, 'D')
print("Ertangi kun:", ertaga)


Bugun: 2025-02-20
Kecha: 2025-02-19
Ertangi kun: 2025-02-21


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
import numpy as np

# 2016 yil 1-yanvar va 2016 yil 2-fevral orasidagi barcha sanalarni olish
sanalar = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print("2016 yil yanvar oyidagi barcha sanalar:")
print(sanalar)


2016 yil yanvar oyidagi barcha sanalar:
['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:


# Musbat sonlardan iborat tasodifiy massiv yaratish
massiv = np.random.random(10) * 10  # 0 dan 10 gacha bo'lgan tasodifiy sonlar
print("Tasodifiy massiv:")
print(massiv)

# 1. % operatori yordamida butun qismini olish
butun_qism_mod = massiv % 1
print("\n% operatori yordamida butun qism:", butun_qism_mod)

# 2. np.floor yordamida butun qismini olish
butun_qism_floor = np.floor(massiv)
print("\nnp.floor yordamida butun qism:", butun_qism_floor)

# 3. astype yordamida butun qismini olish
butun_qism_astype = massiv.astype(int)
print("\nastype yordamida butun qism:", butun_qism_astype)

# 4. np.trunc yordamida butun qismini olish
butun_qism_trunc = np.trunc(massiv)
print("\nnp.trunc yordamida butun qism:", butun_qism_trunc)


Tasodifiy massiv:
[0.18943569 9.83148568 8.6594564  1.08708312 9.15099518 0.95190102
 9.01547113 8.67679923 2.24793834 3.21045551]

% operatori yordamida butun qism: [0.18943569 0.83148568 0.6594564  0.08708312 0.15099518 0.95190102
 0.01547113 0.67679923 0.24793834 0.21045551]

np.floor yordamida butun qism: [0. 9. 8. 1. 9. 0. 9. 8. 2. 3.]

astype yordamida butun qism: [0 9 8 1 9 0 9 8 2 3]

np.trunc yordamida butun qism: [0. 9. 8. 1. 9. 0. 9. 8. 2. 3.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:


# Ixtiyoriy kichik massiv yaratish
massiv = np.random.random(100)  # 100 ta tasodifiy sonlardan iborat massiv
print("Massiv:")
print(massiv)

# np.sum funksiyasi yordamida yig'indisini hisoblash
sum_1 = np.sum(massiv)
print("\nnp.sum yordamida yig'indi:")
print(sum_1)

# np.add.reduce yordamida yig'indisini hisoblash
sum_2 = np.add.reduce(massiv)
print("\nnp.add.reduce yordamida yig'indi:")
print(sum_2)

# Yig'indilarni solishtirish
print("\nYig'indilar tengmi?:", np.isclose(sum_1, sum_2))


Massiv:
[0.66731776 0.20089045 0.3967227  0.07485249 0.69417135 0.47068031
 0.93480717 0.92137306 0.39804491 0.65132121 0.060599   0.57936653
 0.35879118 0.8095728  0.3468096  0.13507254 0.29897467 0.09136589
 0.79485052 0.69895153 0.88134989 0.9202248  0.95142108 0.20877454
 0.55712306 0.19205217 0.09353283 0.13044024 0.05863311 0.77578159
 0.81723654 0.47348997 0.57878574 0.11271718 0.14754249 0.18546698
 0.0459719  0.32198175 0.05664154 0.53371649 0.87827583 0.13773595
 0.78461987 0.46153346 0.50012552 0.92233478 0.21298294 0.07924397
 0.44217533 0.53013866 0.87701024 0.90579462 0.08751015 0.98884245
 0.90851787 0.30628795 0.87308739 0.6511989  0.60014668 0.38860046
 0.83861181 0.5323452  0.55528003 0.10482372 0.58492382 0.93678354
 0.34475168 0.45437142 0.32763911 0.14634553 0.21607729 0.21010349
 0.93525822 0.73300405 0.29736796 0.12443117 0.36472277 0.6266799
 0.86725434 0.1907949  0.2499692  0.17211273 0.5522585  0.84280457
 0.69307293 0.89086704 0.94083356 0.95657969 0.22689689

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
import numpy as np

# 1, 2, 3, 4, 5 vektori
vektor = np.array([1, 2, 3, 4, 5])

# Har bir qiymat orasiga 3 ta nol kiritish
yangi_vektor = np.zeros(vektor.size * 4 - 1)  # Bo'sh joy yaratish
yangi_vektor[::4] = vektor  # Har 4-kichik indeksga original vektor qiymatlarini joylash

print("Yangi vektor:")
print(yangi_vektor)


Yangi vektor:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

# a massivini yaratish
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# b massivini yaratish: har bir qatorda 4 ta element bo'lishi kerak
b = as_strided(a, shape=(11, 4), strides=(a.strides[0], a.strides[0]))

print("b massiv:")
print(b)


b massiv:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:


# Ixtiyoriy sonlardan tashkil topgan massiv yaratish
massiv = np.random.randint(1, 10, size=20)  # 1 dan 10 gacha bo'lgan tasodifiy sonlar, 20 ta element
print("Massiv:")
print(massiv)

# np.bincount yordamida qiymatlarning chastotasini hisoblash
chastota = np.bincount(massiv)
print("\nQiymatlarning chastotasi:")
print(chastota)

# Eng ko'p uchraydigan qiymatni topish
eng_ko_p_uchraydigan = np.argmax(chastota)
print("\nEng ko'p uchraydigan qiymat:", eng_ko_p_uchraydigan)


Massiv:
[1 4 4 2 1 8 6 9 2 8 3 7 1 7 9 1 6 8 1 2]

Qiymatlarning chastotasi:
[0 5 3 1 2 0 2 2 3 2]

Eng ko'p uchraydigan qiymat: 1


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:


# 1. np.random.rand(d0, d1, ..., dn) - 0 va 1 orasidagi tasodifiy sonlar bilan massiv yaratish
# Bu funksiyaning yordamida 0 va 1 orasidagi tasodifiy sonlardan iborat massiv yaratish mumkin.
massiv1 = np.random.rand(3, 4)  # 3x4 o'lchamdagi massiv
print("1. np.random.rand yordamida massiv:")
print(massiv1)

# 2. np.random.randint(low, high, size) - Berilgan oraliqda butun sonlar yaratish
# Bu funksiya ko'rsatilgan oraliq (low, high) orasida butun sonlardan iborat massiv yaratadi.
massiv2 = np.random.randint(1, 10, 5)  # 1 dan 10 gacha bo'lgan butun sonlar, 5 elementli massiv
print("\n2. np.random.randint yordamida massiv:")
print(massiv2)

# 3. np.random.randn(d0, d1, ..., dn) - Normal taqsimot bo'yicha tasodifiy sonlar yaratish
# Bu funksiya normal taqsimot (0, 1) bo'yicha tasodifiy sonlar yaratadi, ya'ni o'rtacha 0 va dispersiyasi 1.
massiv3 = np.random.randn(3, 4)  # 3x4 o'lchamdagi normal taqsimot bo'yicha tasodifiy sonlar
print("\n3. np.random.randn yordamida massiv:")
print(massiv3)

# 4. np.random.choice(a, size, replace) - Berilgan massivdan tasodifiy elementlarni tanlash
# Bu funksiya a massividan tasodifiy tanlovlar qiladi. `replace=False` parametrini o'rnatish bilan bir xil elementlarni qayta tanlashni oldini oladi.
massiv4 = np.random.choice([1, 2, 3, 4, 5], size=3, replace=False)  # 1, 2, 3, 4, 5 elementlaridan 3 ta tasodifiy sonni tanlash
print("\n4. np.random.choice yordamida massiv:")
print(massiv4)


1. np.random.rand yordamida massiv:
[[0.03745242 0.77234758 0.02019083 0.61402684]
 [0.20171816 0.08947481 0.0371022  0.7382531 ]
 [0.56852515 0.4138984  0.88696343 0.28849658]]

2. np.random.randint yordamida massiv:
[5 3 4 3 3]

3. np.random.randn yordamida massiv:
[[ 0.39168957  0.70409824 -1.02055142  1.04338779]
 [ 0.33595353  0.48512013 -2.82986783  0.01975602]
 [-1.08212542 -0.76505211  1.40017787 -0.97080713]]

4. np.random.choice yordamida massiv:
[4 2 5]
